/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LocationWhereUniqueInput } from "../../location/base/LocationWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ShiftWhereUniqueInput } from "../../shift/base/ShiftWhereUniqueInput";
import { WorkerWhereUniqueInput } from "../../worker/base/WorkerWhereUniqueInput";

@InputType()
class AttendanceRecordWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  checkInTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  checkOutTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LocationWhereUniqueInput)
  @IsOptional()
  @Field(() => LocationWhereUniqueInput, {
    nullable: true,
  })
  location?: LocationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  qrCode?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  qrCodeExpiration?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ShiftWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ShiftWhereUniqueInput)
  @IsOptional()
  @Field(() => ShiftWhereUniqueInput, {
    nullable: true,
  })
  shift?: ShiftWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => WorkerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkerWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkerWhereUniqueInput, {
    nullable: true,
  })
  worker?: WorkerWhereUniqueInput;
}

export { AttendanceRecordWhereInput as AttendanceRecordWhereInput };
